version: 2

models:
  - name: dim_athletes
    description: "Dimension table containing detailed information about athletes, including personal details, address, and related identifiers."
    columns:
      - name: created_at
        description: "The timestamp when the athlete record was created."
      - name: expired
        description: "Indicates if the athlete's membership is expired."
      - name: expiry_date
        description: "The date of membership expiry."
      - name: athlete_id
        description: "Primary key for the athlete."
        data_tests:
          - not_null
      - name: dob
        description: "Date of birth."
      - name: name
        description: "Full name of the athlete."
      - name: updated_at
        description: "Last update timestamp."
      - name: gender
        description: "Gender of the athlete."
      - name: address
        description: "Mailing address."
      - name: suburb
        description: "Suburb of residence."
      - name: state
        description: "State of residence."
      - name: postcode
        description: "Postcode."
      - name: are_lshkwaal_or_torres_strait_islander
        description: "Aboriginal/Torres Strait Islander indicator."
      - name: user_id
        description: "Foreign key to dim_users."
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_users')
                field: user_id
      - name: series_id
        description: "Foreign key to dim_series."
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_series')
                field: series_id
      - name: division_id
        description: "Foreign key to dim_division."
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_division')
                field: division_id
      - name: eventdivision_id
        description: "Foreign key to dim_eventdivision."
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_eventdivision')
                field: eventdivision_id

  - name: dim_division
    description: "Dimension table for competition divisions."
    columns:
      - name: division_id
        description: "Unique identifier for the division."
        data_tests:
          - unique
          - not_null
      - name: division_name
        description: "Name of the division."

  - name: dim_eventdivision
    description: "Dimension table for specific event divisions."
    columns:
      - name: eventdivision_id
        description: "Unique identifier for the event division."
        data_tests:
          - unique
          - not_null
      - name: division_id
        description: "Referential link to the parent division."
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_division')
                field: division_id

  - name: dim_series
    description: "Dimension table for competition series."
    columns:
      - name: series_id
        description: "Unique identifier for the series."
        data_tests:
          - unique
          - not_null
      - name: series_name
        description: "Name of the series."

  - name: dim_series_organization
    description: "Dimension table for series management organizations."
    columns:
      - name: series_id
        description: "Unique identifier for the series."
        data_tests:
          - unique
          - not_null
          - relationships:
              arguments:
                to: ref('dim_series')
                field: series_id
      - name: organization_name
        description: "Name of the organization."
      - name: organization_shortname
        description: "Short name/Abbreviation."
      - name: organization_email
        description: "Contact email."
      - name: organization_sporttype
        description: "Sport type managed."

  - name: dim_users
    description: "Dimension table for user accounts associated with athletes."
    columns:
      - name: user_id
        description: "Unique identifier for the user."
        data_tests:
          - unique
          - not_null
      - name: user_name
        description: "Name of the user."
      - name: user_email
        description: "Email address."
      - name: user_phone
        description: "Phone number."
      - name: user_role
        description: "User role."
